# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-20 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='\u59d3\u540d')),
                ('mobile', models.CharField(max_length=11, verbose_name='\u624b\u673a')),
                ('email', models.CharField(max_length=30, verbose_name='\u90ae\u7bb1')),
                ('company', models.CharField(max_length=30, verbose_name='\u516c\u53f8')),
                ('position', models.CharField(max_length=30, verbose_name='\u804c\u4f4d')),
            ],
            options={
                'verbose_name': '\u5ba2\u6237\u7ba1\u7406',
                'verbose_name_plural': '\u5ba2\u6237\u7ba1\u7406',
            },
        ),
    ]
