# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corpus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corpus_name', models.CharField(max_length=100, unique=True, verbose_name='\u6807\u9898')),
                ('creater', models.CharField(max_length=100, verbose_name='\u521b\u5efa\u4eba')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('memo', models.CharField(max_length=100, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'verbose_name': '\u9879\u76ee\u7ba1\u7406',
                'verbose_name_plural': '\u9879\u76ee\u7ba1\u7406',
            },
        ),
    ]
