# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 07:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpus_list', '0003_p8'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='p6',
            new_name='p1',
        ),
    ]
