# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 07:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpus_list', '0005_auto_20160616_1536'),
    ]

    operations = [
        migrations.DeleteModel(
            name='p6',
        ),
    ]
