# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-18 03:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpus_list', '0010_p2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='p2',
        ),
    ]
