# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-18 03:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpus_list', '0013_auto_20160618_1111'),
    ]

    operations = [
        migrations.DeleteModel(
            name='p4',
        ),
    ]
