# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus_list', '0018_p8'),
    ]

    operations = [
        migrations.CreateModel(
            name='p9',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='\u95ee\u9898')),
                ('answer', models.CharField(max_length=500, verbose_name='\u7b54\u6848')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u52a0\u5165\u65f6\u95f4')),
                ('status', models.CharField(choices=[(b'0', b'\xe5\xbe\x85\xe5\xad\xa6\xe4\xb9\xa0'), (b'1', b'\xe5\xb7\xb2\xe5\xad\xa6\xe4\xb9\xa0')], default=b'0', editable=False, max_length=12, verbose_name='\u5b66\u4e60\u72b6\u6001')),
                ('common_status', models.CharField(choices=[(b'0', b'\xe9\x9d\x9e\xe5\xb8\xb8\xe8\xa7\x81\xe9\x97\xae\xe9\xa2\x98'), (b'1', b'\xe5\xb8\xb8\xe8\xa7\x81\xe9\x97\xae\xe9\xa2\x98')], default=b'0', max_length=12, verbose_name='\u662f\u5426\u5e38\u89c1')),
                ('node', models.CharField(blank=True, default=b'', editable=False, max_length=100, verbose_name='\u8282\u70b9ID')),
                ('threshold', models.CharField(default=b'0.2', help_text='\u8bf7\u8f93\u51650~1\u7684\u503c\u3002', max_length=10, verbose_name='\u9608\u503c')),
            ],
            options={
                'verbose_name': '\u6d4b\u8bd54',
                'verbose_name_plural': '\u6d4b\u8bd54',
            },
        ),
    ]
